### ISSUE TITLE
Next Steps [ESP SITE]

### ISSUE THREAD

**Issue by cssummercampdr** [cssummercampd-r/cssummercampsite#5]
- [x] Figure out domain situation
- [x] Final run through of site
- [x] Fix girls portfolios

**Comment by maypena** [comment]
I fixed all the girls' portfolios, at least the errors I caught with them.

**Comment by arrismo** [comment]
- [x] Take off Donate Button
- [x] Fix Gallery (have a button to view more only 2-3 photos in carousel)
